// Dermatology vocabulary used to make dictation accurate on clinical terms.
//
// The list feeds two separate mechanisms, which have very different size budgets:
//
// 1. Contextual biasing (`BIASING_TERMS`). Handed to the recognizer before it
//    listens, so it weights these phrasings higher. Both platforms degrade if
//    this list is large -- Apple's `contextualStrings` and Android's
//    EXTRA_BIASING_STRINGS are meant for a focused set, not a dictionary. Keep
//    it to the terms a dermatologist actually says out loud, most-confusable
//    first.
// 2. Post-correction (`CORRECTION_LEXICON`). Runs locally over the final
//    transcript, so it costs nothing at recognition time and can be much
//    broader. Everything in the biasing list is also a correction target.
//
// Sources: DermNet A-Z topic index and morphology terminology
// (https://dermnetnz.org/topics), plus common dermatology formulary drugs.

/** Lesion morphology -- the descriptive vocabulary of a skin exam. */
const MORPHOLOGY = [
  "macule",
  "macules",
  "patch",
  "patches",
  "papule",
  "papules",
  "nodule",
  "nodules",
  "plaque",
  "plaques",
  "vesicle",
  "vesicles",
  "pustule",
  "pustules",
  "bulla",
  "bullae",
  "cyst",
  "cysts",
  "abscess",
  "weal",
  "wheal",
  "wheals",
  "comedone",
  "comedones",
  "open comedones",
  "closed comedones",
  "milia",
  "milium",
  "burrow",
  "burrows",
  "telangiectasia",
  "telangiectasias",
  "petechiae",
  "purpura",
  "ecchymosis",
  "erythema",
  "erythematous",
  "annular",
  "arcuate",
  "serpiginous",
  "reticulate",
  "livedo reticularis",
  "targetoid",
  "umbilicated",
  "verrucous",
  "papillomatous",
  "pedunculated",
  "sessile",
  "indurated",
  "induration",
  "fluctuant",
  "scaling",
  "desquamation",
  "hyperkeratosis",
  "hyperkeratotic",
  "lichenification",
  "lichenified",
  "crusting",
  "crusted",
  "excoriation",
  "excoriations",
  "excoriated",
  "erosion",
  "erosions",
  "fissure",
  "fissures",
  "fissuring",
  "ulcer",
  "ulcers",
  "ulceration",
  "ulcerated",
  "eschar",
  "sinus tract",
  "granulation tissue",
  "granuloma",
  "granulomatous",
  "atrophy",
  "atrophic",
  "hypertrophy",
  "hypertrophic",
  "sclerosis",
  "sclerotic",
  "poikiloderma",
  "hyperpigmentation",
  "hyperpigmented",
  "hypopigmentation",
  "hypopigmented",
  "depigmentation",
  "depigmented",
  "dyspigmentation",
  "postinflammatory hyperpigmentation",
  "erythroderma",
  "exfoliation",
  "xerosis",
  "pruritus",
  "pruritic",
  "photodistributed",
  "koebnerisation",
  "Koebner phenomenon",
  "Nikolsky sign",
  "Auspitz sign",
  "dermographism",
  "satellite lesions",
  "collarette of scale",
  "silvery scale",
  "honey coloured crust",
  "well demarcated",
  "ill defined",
  "confluent",
  "coalescing",
];

/** Diagnoses and named conditions. */
const CONDITIONS = [
  // Acne / follicular
  "acne",
  "acne vulgaris",
  "comedonal acne",
  "nodulocystic acne",
  "cystic acne",
  "acne keloidalis nuchae",
  "rosacea",
  "rhinophyma",
  "periorificial dermatitis",
  "perioral dermatitis",
  "periocular dermatitis",
  "hidradenitis suppurativa",
  "folliculitis",
  "folliculitis barbae",
  "folliculitis decalvans",
  "scalp folliculitis",
  "Malassezia folliculitis",
  "pseudofolliculitis barbae",
  "keratosis pilaris",
  "furuncle",
  "carbuncle",
  "boil",
  "kerion",

  // Eczema / dermatitis
  "eczema",
  "dermatitis",
  "atopic dermatitis",
  "atopic eczema",
  "contact dermatitis",
  "allergic contact dermatitis",
  "irritant contact dermatitis",
  "seborrhoeic dermatitis",
  "seborrheic dermatitis",
  "dyshidrotic eczema",
  "pompholyx",
  "discoid eczema",
  "nummular eczema",
  "venous eczema",
  "stasis dermatitis",
  "asteatotic eczema",
  "hand dermatitis",
  "napkin dermatitis",
  "diaper dermatitis",
  "lichen simplex chronicus",
  "nodular prurigo",
  "prurigo nodularis",
  "juvenile plantar dermatosis",
  "lip lickers dermatitis",
  "intertrigo",
  "granular parakeratosis",

  // Papulosquamous
  "psoriasis",
  "plaque psoriasis",
  "guttate psoriasis",
  "scalp psoriasis",
  "nail psoriasis",
  "genital psoriasis",
  "inverse psoriasis",
  "pustular psoriasis",
  "generalised pustular psoriasis",
  "palmoplantar pustulosis",
  "psoriatic arthritis",
  "lichen planus",
  "oral lichen planus",
  "lichen planopilaris",
  "lichen sclerosus",
  "lichen nitidus",
  "lichenoid keratosis",
  "pityriasis rosea",
  "pityriasis versicolor",
  "tinea versicolor",
  "pityriasis alba",
  "pityriasis lichenoides",
  "pityriasis rubra pilaris",
  "parapsoriasis",
  "Darier disease",
  "Grover disease",
  "transient acantholytic dermatosis",

  // Infections -- fungal
  "tinea",
  "tinea corporis",
  "tinea cruris",
  "tinea pedis",
  "tinea capitis",
  "tinea manuum",
  "tinea faciei",
  "tinea incognito",
  "tinea unguium",
  "onychomycosis",
  "dermatophyte",
  "dermatophytosis",
  "candidiasis",
  "oral candidiasis",
  "cutaneous candidiasis",
  "intertriginous candidiasis",
  "angular cheilitis",
  "erythrasma",

  // Infections -- bacterial / viral / parasitic
  "impetigo",
  "cellulitis",
  "erysipelas",
  "necrotising fasciitis",
  "ecthyma",
  "paronychia",
  "acute paronychia",
  "chronic paronychia",
  "leprosy",
  "Hansen disease",
  "cutaneous tuberculosis",
  "lupus vulgaris",
  "herpes simplex",
  "genital herpes",
  "herpes zoster",
  "shingles",
  "chickenpox",
  "varicella",
  "eczema herpeticum",
  "molluscum contagiosum",
  "viral wart",
  "verruca vulgaris",
  "plantar wart",
  "condyloma acuminatum",
  "hand foot and mouth disease",
  "measles",
  "rubella",
  "roseola",
  "orf",
  "scabies",
  "crusted scabies",
  "Norwegian scabies",
  "pediculosis",
  "head lice",
  "cutaneous larva migrans",
  "leishmaniasis",
  "insect bite reaction",
  "papular urticaria",

  // Pigmentary
  "vitiligo",
  "melasma",
  "chloasma",
  "solar lentigo",
  "lentigines",
  "lentigo",
  "freckles",
  "ephelides",
  "idiopathic guttate hypomelanosis",
  "acanthosis nigricans",
  "Riehl melanosis",
  "lichen planus pigmentosus",
  "ashy dermatosis",
  "periorbital hyperpigmentation",
  "melanonychia",

  // Hair and nails
  "alopecia",
  "alopecia areata",
  "alopecia totalis",
  "alopecia universalis",
  "androgenetic alopecia",
  "male pattern hair loss",
  "female pattern hair loss",
  "telogen effluvium",
  "anagen effluvium",
  "traction alopecia",
  "cicatricial alopecia",
  "scarring alopecia",
  "frontal fibrosing alopecia",
  "central centrifugal cicatricial alopecia",
  "trichotillomania",
  "hirsutism",
  "hypertrichosis",
  "onycholysis",
  "onychogryphosis",
  "onychopapilloma",
  "subungual hyperkeratosis",
  "nail pitting",
  "Beau lines",
  "koilonychia",
  "clubbing",
  "ingrown toenail",

  // Urticaria / drug / immunobullous / autoimmune
  "urticaria",
  "chronic spontaneous urticaria",
  "angioedema",
  "urticarial vasculitis",
  "erythema multiforme",
  "Stevens Johnson syndrome",
  "toxic epidermal necrolysis",
  "DRESS syndrome",
  "drug hypersensitivity syndrome",
  "fixed drug eruption",
  "morbilliform drug reaction",
  "maculopapular rash",
  "exanthem",
  "erythema nodosum",
  "erythema annulare centrifugum",
  "pemphigus",
  "pemphigus vulgaris",
  "pemphigus foliaceus",
  "bullous pemphigoid",
  "dermatitis herpetiformis",
  "linear IgA disease",
  "cutaneous lupus erythematosus",
  "discoid lupus erythematosus",
  "systemic lupus erythematosus",
  "subacute cutaneous lupus",
  "dermatomyositis",
  "morphoea",
  "morphea",
  "scleroderma",
  "systemic sclerosis",
  "Raynaud phenomenon",
  "cutaneous vasculitis",
  "Henoch Schonlein purpura",
  "IgA vasculitis",
  "Behcet disease",
  "sarcoidosis",
  "granuloma annulare",
  "necrobiosis lipoidica",
  "pyoderma gangrenosum",
  "Sweet syndrome",
  "vitiligo vulgaris",
  "mastocytosis",
  "urticaria pigmentosa",

  // Neoplasms -- benign and malignant
  "seborrhoeic keratosis",
  "seborrheic keratosis",
  "actinic keratosis",
  "solar keratosis",
  "cutaneous horn",
  "dermatofibroma",
  "epidermoid cyst",
  "pilar cyst",
  "sebaceous cyst",
  "sebaceous hyperplasia",
  "skin tag",
  "acrochordon",
  "cherry angioma",
  "Campbell de Morgan spot",
  "pyogenic granuloma",
  "infantile haemangioma",
  "port wine stain",
  "venous lake",
  "lipoma",
  "neurofibroma",
  "keratoacanthoma",
  "melanocytic naevus",
  "melanocytic nevus",
  "congenital melanocytic naevus",
  "dysplastic naevus",
  "atypical naevus",
  "halo naevus",
  "blue naevus",
  "Spitz naevus",
  "naevus sebaceous",
  "becker naevus",
  "basal cell carcinoma",
  "squamous cell carcinoma",
  "intraepidermal squamous cell carcinoma",
  "Bowen disease",
  "melanoma",
  "superficial spreading melanoma",
  "nodular melanoma",
  "acral lentiginous melanoma",
  "lentigo maligna",
  "lentigo maligna melanoma",
  "amelanotic melanoma",
  "Kaposi sarcoma",
  "mycosis fungoides",
  "cutaneous T cell lymphoma",
  "Merkel cell carcinoma",
  "dermatofibrosarcoma protuberans",

  // Misc
  "keloid",
  "hypertrophic scar",
  "hyperhidrosis",
  "bromhidrosis",
  "miliaria",
  "heat rash",
  "chilblains",
  "perniosis",
  "lipodermatosclerosis",
  "venous insufficiency",
  "venous ulcer",
  "arterial ulcer",
  "pressure ulcer",
  "diabetic foot ulcer",
  "aphthous ulcer",
  "geographic tongue",
  "chondrodermatitis nodularis",
  "notalgia paraesthetica",
  "xanthelasma",
  "xanthoma",
  "striae",
  "striae distensae",
  "ichthyosis",
  "ichthyosis vulgaris",
  "epidermolysis bullosa",
  "hailey hailey disease",
  "pilonidal sinus",
  "vulval intraepithelial neoplasia",
  "balanitis",
  "phimosis",
];

/** Body sites and anatomical descriptors used when localising a lesion. */
const ANATOMY = [
  "scalp",
  "vertex",
  "occiput",
  "occipital",
  "temple",
  "forehead",
  "glabella",
  "eyebrow",
  "eyelid",
  "periorbital",
  "nasolabial fold",
  "nasal bridge",
  "alar",
  "malar",
  "cheek",
  "philtrum",
  "vermilion border",
  "chin",
  "jawline",
  "mandible",
  "preauricular",
  "postauricular",
  "helix",
  "antihelix",
  "tragus",
  "concha",
  "earlobe",
  "neck",
  "nape",
  "nuchal",
  "supraclavicular",
  "clavicle",
  "shoulder",
  "deltoid",
  "axilla",
  "axillae",
  "axillary",
  "chest",
  "sternum",
  "presternal",
  "breast",
  "inframammary",
  "inframammary fold",
  "abdomen",
  "periumbilical",
  "umbilicus",
  "flank",
  "back",
  "upper back",
  "lower back",
  "interscapular",
  "lumbar",
  "sacral",
  "sacrum",
  "buttock",
  "gluteal",
  "natal cleft",
  "groin",
  "inguinal",
  "inguinal fold",
  "genitalia",
  "vulva",
  "vulval",
  "scrotum",
  "penis",
  "perineum",
  "perianal",
  "arm",
  "upper arm",
  "forearm",
  "elbow",
  "antecubital fossa",
  "extensor surface",
  "flexor surface",
  "flexural",
  "wrist",
  "hand",
  "dorsum of the hand",
  "palm",
  "palmar",
  "web space",
  "finger",
  "digit",
  "thumb",
  "nail fold",
  "proximal nail fold",
  "nail bed",
  "nail plate",
  "nail matrix",
  "cuticle",
  "periungual",
  "subungual",
  "thigh",
  "knee",
  "popliteal fossa",
  "shin",
  "pretibial",
  "calf",
  "ankle",
  "malleolus",
  "gaiter area",
  "foot",
  "dorsum of the foot",
  "sole",
  "plantar",
  "heel",
  "toe",
  "toe web",
  "interdigital",
  "acral",
  "trunk",
  "extremities",
  "mucosa",
  "buccal mucosa",
  "oral mucosa",
  "tongue",
  "hard palate",
  "conjunctiva",
  "intertriginous",
  "seborrhoeic areas",
  "sun exposed areas",
  "photoexposed",
  "bilateral",
  "unilateral",
  "symmetrical",
  "asymmetrical",
  "proximal",
  "distal",
  "medial",
  "lateral",
  "anterior",
  "posterior",
  "dorsal",
  "ventral",
  "localised",
  "generalised",
  "widespread",
  "diffuse",
  "disseminated",
];

/** Topical, systemic and procedural therapeutics. */
const DRUGS = [
  // Topical corticosteroids
  "hydrocortisone",
  "hydrocortisone butyrate",
  "clobetasol",
  "clobetasol propionate",
  "clobetasone",
  "betamethasone",
  "betamethasone valerate",
  "betamethasone dipropionate",
  "mometasone",
  "mometasone furoate",
  "fluocinolone",
  "fluocinonide",
  "triamcinolone",
  "triamcinolone acetonide",
  "desonide",
  "halobetasol",
  "fluticasone",
  "methylprednisolone aceponate",

  // Topical non steroidal
  "tacrolimus",
  "pimecrolimus",
  "calcineurin inhibitor",
  "crisaborole",
  "ruxolitinib cream",
  "calcipotriol",
  "calcipotriene",
  "coal tar",
  "dithranol",
  "anthralin",
  "salicylic acid",
  "urea cream",
  "lactic acid",
  "glycolic acid",
  "azelaic acid",
  "benzoyl peroxide",
  "clindamycin",
  "clindamycin phosphate",
  "erythromycin",
  "nadifloxacin",
  "mupirocin",
  "fusidic acid",
  "framycetin",
  "adapalene",
  "tretinoin",
  "tazarotene",
  "trifarotene",
  "retinoid",
  "retinoids",
  "hydroquinone",
  "kojic acid",
  "arbutin",
  "tranexamic acid",
  "niacinamide",
  "nicotinamide",
  "minoxidil",
  "topical minoxidil",
  "finasteride",
  "dutasteride",
  "bimatoprost",
  "eflornithine",
  "ketoconazole",
  "ciclopirox",
  "ciclopirox olamine",
  "clotrimazole",
  "miconazole",
  "luliconazole",
  "sertaconazole",
  "amorolfine",
  "efinaconazole",
  "terbinafine cream",
  "permethrin",
  "benzyl benzoate",
  "crotamiton",
  "malathion",
  "podophyllotoxin",
  "imiquimod",
  "5 fluorouracil",
  "fluorouracil cream",
  "diclofenac gel",
  "silver sulfadiazine",
  "emollient",
  "emollients",
  "moisturiser",
  "moisturizer",
  "ceramide",
  "petrolatum",
  "liquid paraffin",
  "white soft paraffin",
  "sunscreen",
  "broad spectrum sunscreen",
  "SPF",
  "photoprotection",

  // Systemic
  "isotretinoin",
  "acitretin",
  "doxycycline",
  "minocycline",
  "lymecycline",
  "azithromycin",
  "cephalexin",
  "cefalexin",
  "amoxicillin",
  "amoxicillin clavulanate",
  "flucloxacillin",
  "dicloxacillin",
  "trimethoprim",
  "cotrimoxazole",
  "dapsone",
  "colchicine",
  "hydroxychloroquine",
  "chloroquine",
  "prednisolone",
  "prednisone",
  "methotrexate",
  "ciclosporin",
  "cyclosporine",
  "azathioprine",
  "mycophenolate mofetil",
  "apremilast",
  "acyclovir",
  "aciclovir",
  "valacyclovir",
  "valaciclovir",
  "famciclovir",
  "terbinafine",
  "itraconazole",
  "fluconazole",
  "griseofulvin",
  "ivermectin",
  "spironolactone",
  "metformin",
  "cetirizine",
  "levocetirizine",
  "fexofenadine",
  "loratadine",
  "desloratadine",
  "bilastine",
  "hydroxyzine",
  "chlorpheniramine",
  "montelukast",
  "antihistamine",
  "antihistamines",
  "gabapentin",
  "pregabalin",
  "amitriptyline",

  // Biologics and small molecules
  "biologic",
  "biologics",
  "dupilumab",
  "tralokinumab",
  "lebrikizumab",
  "omalizumab",
  "adalimumab",
  "etanercept",
  "infliximab",
  "secukinumab",
  "ixekizumab",
  "brodalumab",
  "ustekinumab",
  "guselkumab",
  "risankizumab",
  "tildrakizumab",
  "bimekizumab",
  "rituximab",
  "JAK inhibitor",
  "Janus kinase inhibitor",
  "upadacitinib",
  "abrocitinib",
  "baricitinib",
  "tofacitinib",
  "ritlecitinib",
  "deucravacitinib",

  // Procedures
  "cryotherapy",
  "liquid nitrogen",
  "electrocautery",
  "electrodesiccation",
  "curettage",
  "curettage and cautery",
  "shave biopsy",
  "punch biopsy",
  "excision biopsy",
  "incisional biopsy",
  "wide local excision",
  "Mohs micrographic surgery",
  "intralesional steroid",
  "intralesional triamcinolone",
  "intralesional injection",
  "chemical peel",
  "TCA peel",
  "microneedling",
  "dermaroller",
  "platelet rich plasma",
  "PRP",
  "laser resurfacing",
  "fractional CO2 laser",
  "Nd YAG laser",
  "KTP laser",
  "pulsed dye laser",
  "Q switched laser",
  "intense pulsed light",
  "phototherapy",
  "narrowband UVB",
  "UVB phototherapy",
  "PUVA",
  "photodynamic therapy",
  "botulinum toxin",
  "dermal filler",
  "hyaluronic acid filler",
  "hair transplant",
  "punch grafting",
  "suction blister grafting",
  "melanocyte transfer",

  // Investigations
  "dermoscopy",
  "dermatoscopy",
  "dermatoscope",
  "Wood lamp",
  "Wood lamp examination",
  "patch test",
  "patch testing",
  "prick test",
  "skin biopsy",
  "histopathology",
  "direct immunofluorescence",
  "KOH mount",
  "potassium hydroxide mount",
  "fungal culture",
  "Tzanck smear",
  "slit skin smear",
  "trichoscopy",
  "hair pull test",
  "ANA",
  "antinuclear antibody",
  "complete blood count",
  "liver function test",
  "renal function test",
  "thyroid function test",
  "serum ferritin",
  "vitamin D",
  "vitamin B12",
  "HbA1c",
  "lipid profile",
];

/** Clinical shorthand, scores and phrasing that recur in consultation notes. */
const CLINICAL = [
  "PASI score",
  "EASI score",
  "SCORAD",
  "DLQI",
  "Fitzpatrick skin type",
  "skin phototype",
  "Breslow thickness",
  "biopsy proven",
  "clinically consistent with",
  "differential diagnosis",
  "provisional diagnosis",
  "review in two weeks",
  "review in four weeks",
  "review in six weeks",
  "follow up in one month",
  "follow up in three months",
  "as needed",
  "twice daily",
  "once daily",
  "three times daily",
  "at bedtime",
  "in the morning",
  "apply thinly",
  "apply sparingly",
  "taper",
  "tapering dose",
  "for two weeks",
  "for four weeks",
  "for six weeks",
  "for three months",
  "milligrams",
  "micrograms",
  "millilitres",
  "milligrams per kilogram",
  "percent",
  "topical",
  "topically",
  "systemic",
  "oral",
  "orally",
  "intralesional",
  "subcutaneous",
  "intramuscular",
  "flare",
  "flare up",
  "relapse",
  "remission",
  "recurrence",
  "resolved",
  "resolving",
  "improving",
  "worsening",
  "no improvement",
  "partial response",
  "good response",
  "itching",
  "burning",
  "stinging",
  "soreness",
  "duration of symptoms",
  "onset",
  "gradual onset",
  "sudden onset",
  "since childhood",
  "family history",
  "personal history of atopy",
  "atopic",
  "asthma",
  "allergic rhinitis",
  "drug allergy",
  "no known drug allergy",
  "counselled",
  "counselling given",
  "advised sun protection",
  "advised emollients",
  "patient education",
  "informed consent taken",
  "referred to",
  "for review",
];

/**
 * Every term we are willing to correct a transcript towards.
 * Deduplicated because several categories legitimately overlap.
 */
export const CORRECTION_LEXICON: readonly string[] = Array.from(
  new Set([
    ...MORPHOLOGY,
    ...CONDITIONS,
    ...ANATOMY,
    ...DRUGS,
    ...CLINICAL,
  ]),
);

/**
 * Words the recognizer reliably gets wrong in ways fuzzy matching cannot fix,
 * because what it heard is itself a valid, common English word. Applied as an
 * exact substitution, so keep entries unambiguous in a clinical note.
 */
export const HOMOPHONE_CORRECTIONS: Readonly<Record<string, string>> = {
  legion: "lesion",
  legions: "lesions",
  "lee sion": "lesion",
  "at optic": "atopic",
  "a topic": "atopic",
  "so riasis": "psoriasis",
  "sir iasis": "psoriasis",
  "tinier": "tinea",
  "tenea": "tinea",
  "tin ear": "tinea",
  "acme": "acne",
  "excema": "eczema",
  "exema": "eczema",
  "eggzema": "eczema",
  "rasacea": "rosacea",
  "rose ausha": "rosacea",
  "prurigo nodular": "prurigo nodularis",
  "pro ritis": "pruritus",
  "pruritis": "pruritus",
  "erethema": "erythema",
  "eritema": "erythema",
  "malaise ezia": "Malassezia",
  "steroid cream": "steroid cream",
  "mole askum": "molluscum",
  "vitalgo": "vitiligo",
  "vitiglio": "vitiligo",
  "melasmia": "melasma",
  "alopesia": "alopecia",
  "alopecia rita": "alopecia areata",
  "urticara": "urticaria",
  "kelloid": "keloid",
  "callus": "callus",
  "wheel": "wheal",
  "wheels": "wheals",
  "papel": "papule",
  "papels": "papules",
  "plack": "plaque",
  "plaks": "plaques",
  "macule are": "macular",
  "dermatitus": "dermatitis",
  "cellulitus": "cellulitis",
  "folliculitus": "folliculitis",
  "isotretinoin capsule": "isotretinoin capsule",
  "aisotretinoin": "isotretinoin",
  "terbinafine tablets": "terbinafine tablets",
  "clobitasol": "clobetasol",
  "beta methasone": "betamethasone",
  "mometazone": "mometasone",
  "tacrolimas": "tacrolimus",
  "adapaline": "adapalene",
  "tretinoin cream": "tretinoin cream",
  "hydrocortizone": "hydrocortisone",
  "doxycyclin": "doxycycline",
  "minocyclin": "minocycline",
  "keto conazole": "ketoconazole",
  "flu conazole": "fluconazole",
  "itra conazole": "itraconazole",
  "permethrine": "permethrin",
  "ivermectine": "ivermectin",
  "dupilimab": "dupilumab",
  "methotrexate injection": "methotrexate injection",
  "biopsy proven": "biopsy proven",
  "dermascopy": "dermoscopy",
  "dermoscopy shows": "dermoscopy shows",
  "co2 laser": "CO2 laser",
  "p r p": "PRP",
  "u v b": "UVB",
  "s p f": "SPF",
  "k o h": "KOH",
  "b c c": "BCC",
  "s c c": "SCC",
};

/**
 * The subset handed to the recognizer as contextual biasing hints. Ordered
 * roughly by how often a dermatologist says them and how badly a general model
 * mangles them; the cap keeps us inside what iOS and Android handle gracefully.
 */
const BIASING_PRIORITY: readonly string[] = [
  // Bread-and-butter diagnoses.
  "acne vulgaris",
  "comedonal acne",
  "nodulocystic acne",
  "rosacea",
  "psoriasis",
  "plaque psoriasis",
  "guttate psoriasis",
  "scalp psoriasis",
  "atopic dermatitis",
  "seborrhoeic dermatitis",
  "contact dermatitis",
  "allergic contact dermatitis",
  "irritant contact dermatitis",
  "dyshidrotic eczema",
  "nummular eczema",
  "lichen planus",
  "lichen sclerosus",
  "lichen simplex chronicus",
  "pityriasis rosea",
  "pityriasis versicolor",
  "pityriasis alba",
  "tinea corporis",
  "tinea cruris",
  "tinea pedis",
  "tinea capitis",
  "tinea versicolor",
  "onychomycosis",
  "candidiasis",
  "intertrigo",
  "impetigo",
  "cellulitis",
  "erysipelas",
  "folliculitis",
  "furuncle",
  "hidradenitis suppurativa",
  "herpes zoster",
  "herpes simplex",
  "molluscum contagiosum",
  "viral wart",
  "verruca vulgaris",
  "scabies",
  "urticaria",
  "angioedema",
  "vitiligo",
  "melasma",
  "acanthosis nigricans",
  "alopecia areata",
  "androgenetic alopecia",
  "telogen effluvium",
  "keratosis pilaris",
  "seborrhoeic keratosis",
  "actinic keratosis",
  "dermatofibroma",
  "epidermoid cyst",
  "cherry angioma",
  "melanocytic naevus",
  "basal cell carcinoma",
  "squamous cell carcinoma",
  "melanoma",
  "keloid",
  "hypertrophic scar",
  "granuloma annulare",
  "erythema multiforme",
  "erythema nodosum",
  "fixed drug eruption",
  "bullous pemphigoid",
  "pemphigus vulgaris",
  "vasculitis",
  "hyperhidrosis",
  "paronychia",
  "prurigo nodularis",

  // Morphology -- said constantly, mangled constantly.
  "macule",
  "macules",
  "papule",
  "papules",
  "plaque",
  "plaques",
  "nodule",
  "nodules",
  "vesicle",
  "vesicles",
  "pustule",
  "pustules",
  "bulla",
  "bullae",
  "wheal",
  "comedones",
  "excoriation",
  "excoriations",
  "lichenification",
  "hyperkeratosis",
  "erythema",
  "erythematous",
  "telangiectasia",
  "purpura",
  "petechiae",
  "induration",
  "erosion",
  "ulceration",
  "eschar",
  "scaling",
  "crusting",
  "pruritus",
  "pruritic",
  "xerosis",
  "hyperpigmentation",
  "hypopigmentation",
  "depigmentation",
  "postinflammatory hyperpigmentation",
  "annular",
  "livedo reticularis",
  "dermographism",
  "well demarcated",

  // Drugs -- highest-value biasing, since brand-new molecule names are the
  // single worst category for a general speech model.
  "hydrocortisone",
  "clobetasol propionate",
  "betamethasone valerate",
  "mometasone furoate",
  "triamcinolone acetonide",
  "tacrolimus",
  "pimecrolimus",
  "calcipotriol",
  "salicylic acid",
  "azelaic acid",
  "benzoyl peroxide",
  "clindamycin",
  "mupirocin",
  "fusidic acid",
  "adapalene",
  "tretinoin",
  "tazarotene",
  "hydroquinone",
  "kojic acid",
  "tranexamic acid",
  "niacinamide",
  "minoxidil",
  "finasteride",
  "ketoconazole",
  "clotrimazole",
  "luliconazole",
  "ciclopirox",
  "amorolfine",
  "permethrin",
  "benzyl benzoate",
  "imiquimod",
  "isotretinoin",
  "acitretin",
  "doxycycline",
  "minocycline",
  "azithromycin",
  "cephalexin",
  "dapsone",
  "hydroxychloroquine",
  "prednisolone",
  "methotrexate",
  "ciclosporin",
  "azathioprine",
  "mycophenolate mofetil",
  "apremilast",
  "valacyclovir",
  "terbinafine",
  "itraconazole",
  "fluconazole",
  "griseofulvin",
  "ivermectin",
  "spironolactone",
  "levocetirizine",
  "fexofenadine",
  "hydroxyzine",
  "bilastine",
  "dupilumab",
  "omalizumab",
  "secukinumab",
  "ustekinumab",
  "adalimumab",
  "upadacitinib",
  "baricitinib",
  "emollient",
  "emollients",

  // Procedures and investigations.
  "cryotherapy",
  "electrocautery",
  "punch biopsy",
  "shave biopsy",
  "excision biopsy",
  "intralesional triamcinolone",
  "chemical peel",
  "microneedling",
  "platelet rich plasma",
  "narrowband UVB",
  "phototherapy",
  "dermoscopy",
  "Wood lamp examination",
  "patch testing",
  "KOH mount",
  "Fitzpatrick skin type",

  // Sites that get mangled.
  "axilla",
  "axillae",
  "flexural",
  "extensor surface",
  "antecubital fossa",
  "popliteal fossa",
  "inframammary fold",
  "nasolabial fold",
  "periorbital",
  "periungual",
  "subungual",
  "plantar",
  "acral",
  "intertriginous",
];

/** Hard cap on biasing hints -- past this, recognizers start to degrade. */
const MAX_BIASING_TERMS = 200;

export const BIASING_TERMS: readonly string[] = Array.from(
  new Set(BIASING_PRIORITY),
).slice(0, MAX_BIASING_TERMS);
